In [2]:
import pandas as pd
import numpy as np
import time
import datetime
import math

In [2]:
zone = pd.DataFrame.from_csv("detector_lane_inventory.tsv", sep="\t")

In [3]:
event = pd.read_csv('accidentsAndIncidents.csv').drop(['Unnamed: 0'], axis=1)

In [4]:
event.head()

2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014
0     1    18    22    31    47    40   114   161   278   513   467   279
1     0     2     3     2     2     0    13    10     9    11    10    12
2     1     4     5     1     3    40    83   145   149   119   102   230
3     4    28    24    18    54    63   234   220   220   195   237   486
4     2     5     6     6    16    28    16   131   544   427   496   505

In [5]:
sampleZone = zone[(zone['zone_id'] == 1160) | (zone['zone_id'] == 3232) | (zone['zone_id'] == 3445) | (zone['zone_id'] == 3451) | (zone['zone_id'] == 3532)].reset_index()

In [6]:
zonedf = sampleZone[['lane_id','zone_id','longitude', 'latitude']]

In [7]:
zonedf.head(2)

lane_id  zone_id  longitude   latitude
0      490     1160 -77.446079  38.838402
1      491     1160 -77.446113  38.838421

In [8]:
trials = pd.read_csv('prediction_trials.tsv', header=0, sep='\t')


In [9]:
trials.head(2)

trial_id     nw_lat     nw_lon     se_lat     se_lon  \
0  p_00000001  39.182985 -76.798663  39.170238 -76.778150   
1  p_00000002  39.303607 -76.829335  39.296709 -76.806935   

                       start                        end  
0  2015-02-01T00:00:00-05:00  2015-03-01T00:00:00-05:00  
1  2016-01-08T00:00:00-05:00  2016-01-22T00:00:00-05:00

In [10]:
mypoint = zonedf.as_matrix()
pts = mypoint[:, [2, 3]]

In [11]:
start_time = time.time()

ss = []

for tin in range(len(trials)):
    
    x1, x2 = trials.loc[tin]['nw_lon'], trials.loc[tin]['se_lon']
    y1, y2 = trials.loc[tin]['se_lat'], trials.loc[tin]['nw_lat']


    ll = np.array([x1, y1])  # lower-left
    ur = np.array([x2, y2])  # upper-right

    inidx = np.all(np.logical_and(ll <= pts, pts <= ur), axis=1)
    #inbox = pts[inidx]
    pos = np.where(inidx==True)
    if(len(pos[0]) > 0):
        #print mypoint[pos]
        ss.append((tin, mypoint[pos][0][1]))
    
    
print("--- %s seconds ---" % (time.time() - start_time))

--- 195.99652361869812 seconds ---


In [13]:
sampleZone = pd.DataFrame.from_dict(ss)[1].astype(int)

In [14]:
sampleZone[3300]

3445

In [15]:
sampleTrial = trials.iloc[pd.DataFrame.from_dict(ss)[0].tolist(),:].reset_index()
sampleEvent = event.iloc[pd.DataFrame.from_dict(ss)[0].tolist(),:].reset_index()

In [16]:
sampleEvent.head()

index  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  \
0     53     2    13    17     8    22    29   112   155   249   241   208   
1     56     0     0     1     1     0     7     4    10    22  1465   339   
2     86     2     7    45    17    28    24   102   117   170   164   144   
3    109     1    17    30    11    24    72   197   120   143   121   215   
4    128     2     3    29    12    24    22    99   111   163   141   117   

   2014  
0   274  
1   279  
2   222  
3   363  
4   211

In [3]:
sampleTrial = pd.read_csv('sampleTrial.csv').drop(['Unnamed: 0'], axis=1)
#sampleEvent = pd.read_csv('sampleEvent.csv').drop(['Unnamed: 0'], axis=1)
sampleZone = pd.read_csv('sampleZone.csv').drop(['Unnamed: 0'], axis=1)

In [89]:
event = pd.read_csv('deviceStatus.csv').drop(['Unnamed: 0'], axis=1)

In [90]:
sampleEvent = event.iloc[sampleEvent['index'].tolist()].reset_index()

In [91]:
sampleZone.head(2)

zoneid
0    3532
1    3451

In [92]:
sampleEvent.head()

index  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  \
0     53     0     0     0     0     0     0     0     0     6    10     8   
1     56     0     0     0     0     0    43    65    88   104   180   186   
2     86     0     0     0     0     0     0     0     0     0     0     0   
3    109     0     0     0     0     0     0     0     0     1     2     1   
4    128     0     0     0     0     0     0     0     0     0     0     0   

   2014  
0     2  
1   175  
2     0  
3     0  
4     0

In [93]:
z3232 = pd.DataFrame.from_csv('3232.txt', sep="\t").reset_index()
z3232['year'] = z3232['year'].astype(str).str[:4].astype(int)

In [94]:
z3445= pd.DataFrame.from_csv('3445.txt', sep="\t").reset_index()
z3445['year'] = z3445['year'].astype(str).str[:4].astype(int)

In [95]:
z3451 = pd.DataFrame.from_csv('3451.txt', sep="\t").reset_index()
z3451['year'] = z3451['year'].astype(str).str[:4].astype(int)

In [96]:
z3451 = pd.concat([z3451, pd.DataFrame(z3451.mean()).T, pd.DataFrame(z3451.mean()).T])\
.reset_index().drop('index', axis=1)

In [97]:
z3451['year'].iloc[6] = 2015
z3451['year'].iloc[7] = 2016

In [98]:
z3532 = pd.DataFrame.from_csv('3532.txt', sep="\t").reset_index()
z3532['year'] = z3532['year'].astype(str).str[:4].astype(int)

In [99]:
year = np.array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]).reshape(-1,1)
event = sampleEvent.drop('index', axis=1).as_matrix()

In [100]:
eventmatrix = event[:, 0:11]
event2014 = sampleEvent['2014'].as_matrix()

In [101]:
event2014

array([  2, 175,   0, ...,   0,   0,   1], dtype=int64)

In [102]:
from sklearn.linear_model import Ridge

In [115]:
predict = []
error = []

for i in range(len(sampleTrial)):
    if(sampleZone['zoneid'][i]==3232):
        zoneMatrix = z3232.as_matrix()[:, :]
    
    if(sampleZone['zoneid'][i]==3445):
        zoneMatrix = z3445.as_matrix()[:, :]
        
    if(sampleZone['zoneid'][i]==3451):
        zoneMatrix = z3451.as_matrix()[:, :]
        
    if(sampleZone['zoneid'][i]==3532):
        zoneMatrix = z3532.as_matrix()[:, :]
        
    features = np.concatenate((year, np.concatenate((np.zeros((6,3)), zoneMatrix[:,1:])) ), axis=1)
    features = year
    xtrain = features[:-3,:]
    ytrain = eventmatrix[i]
    xtest = features[-3:-2,:]
    ytest = event2014[i]
    
    #if(np.count_nonzero(ytrain) > 5):
    #    clf = Ridge(alpha=15)
    #else:
    clf = Ridge(alpha=1)
    
    clf.fit(xtrain, ytrain)    
    predict.append(clf.predict(xtest)[0])
    error.append(((clf.predict(xtest)[0] - ytest) ** 2))
    


In [116]:
np.sqrt(np.sum(error)/len(error)) #device

19.446565343545881

In [88]:
np.sqrt(np.sum(error)/len(error)) #traffic

6.9853715064554995

In [24]:
np.sqrt(np.sum(error)/len(error)) #accidents

172.29567950715654

In [40]:
np.sqrt(np.sum(error)/len(error)) #road

21.535706014276332

In [56]:
np.sqrt(np.sum(error)/len(error)) #precip

0.19722691682769963

In [72]:
np.sqrt(np.sum(error)/len(error)) #obstruct

14.031937229988191

In [117]:
valError = 71.61

In [118]:
valError

71.61

In [141]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [153]:
np.array([[5,8],[5,6]])

array([[5, 8],
       [5, 6]])

In [142]:
x = np.insert(a, [1,2], [[5,8],[5,6]], axis=0)
x

array([[1, 1],
       [5, 8],
       [2, 2],
       [5, 6],
       [3, 3]])

In [144]:
np.delete(x, np.add([1,2], [1,2]), axis=0)

array([[1, 1],
       [5, 8],
       [5, 6]])

In [139]:
np.add([1,2], 1)

array([2, 3])

In [150]:
ind = [7, 8, 10, 11, 12, 13]

In [152]:
a = np.zeros((14,5))

In [156]:
b = np.ones((6, 5))

In [157]:
x = np.insert(a, ind, b, axis=0)

In [170]:
np.delete(np.insert(a, ind, b, axis=0), np.add(ind, [j+1 for j in range(len(ind))]), axis=0)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [167]:
np.add(ind, [j+1 for j in range(len(ind))])

array([ 8, 10, 13, 15, 17, 19])

In [166]:
[j+1 for j in range(len(ind))]

[1, 2, 3, 4, 5, 6]